import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="font-bold flex flex-col justify-center items-center h-screen w-full">
        <input type="text" placeholder="email" />
        <input type="text" placeholder="password" />
        <div className="flex gap-x-10">
          <button
            onClick={() => {
              console.log("clicked");
            }}
          >
            submit
          </button>
          <button
            onClick={async () => {
              const res = await fetch("http://localhost:3009/p", {
                method: "POST",
                mode: "cors",
                headers: {
                  "Content-Type": "application/json",
                },
              });
              console.log(res);
            }}
          >
            api
          </button>
        </div>
      </main>
    </>
  );
}
